### ISSUE TITLE
🐞 Master Style Element has no highlighting and auto hinting

### ISSUE THREAD

**Issue by 1aron** [master-co/css#136] opened 2023-01-11 08:13 UTC
### Description

<img width="1222" alt="Screenshot 2023-01-11 at 4 11 07 PM" src="https://user-images.githubusercontent.com/33840671/211752775-bc3c10d1-4a6e-4961-8c86-42a76a5daeb2.png">

### System Informations

macOS

**Comment by itsezc** [comment] 2023-01-22 12:11
Duplicate of #113

**Closed as completed by itsezc** 2023-01-22 12:12 UTC
Labels: language service
